### ISSUE TITLE
Lustige Exceptions bei Tapping?

### ISSUE THREAD

**Issue by IrisF** [IrisF/FingerDingApp#21]
Beim Daten sammeln ist die App ein paar mal abgestuerzt, aber irgendwie immer an anderen Stellen (mal Nullpointer, mal ArrayIndexOutOfBound).

**Comment by JonasMa** [comment]
ACH UND DU FINDEST DAS LUSTIG?????????????????

**Comment by JonasMa** [comment]
Lag vermutlich an deiner alten Variante, da ich pushen vergessen hatte. Kann ich so nämlich nicht nachvollziehen
