### ISSUE TITLE
Latin Square kaputt

### ISSUE THREAD

**Issue by IrisF** [IrisF/FingerDingApp#27]
Immer gleiche Reihenfolge

**Comment by pranges** [comment]
Sorry sorry sorry hab wohl aus versehen meine Manipulation zum zooming testen mit gepusht ... Im activity manager wird für den Zugriff auf das square vermutlich gerade eine feste Ziffer anstatt der userID verwendet ...

**Comment by pranges** [comment]
sollte gefixt sein :)
