### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by JonasMa** [IrisF/FingerDingApp#4]
Testbild auf bestimmte Größe größer zoomen.

**Comment by pranges** [comment]
TBD: Naming Conventions?
Einheitliche Touch-Erkennung?

**Comment by pranges** [comment]
Zooming: 
- Faktor einrechnen, nicht nur schrittweise vergrößern
- Rahmen setzen
- auch rückwärtige Geste erkennen?

**Comment by pranges** [comment]
TODO: recherchieren wegen Scaling Daten
