### ISSUE TITLE
Datenbankhadler

### ISSUE THREAD

**Issue by JonasMa** [IrisF/FingerDingApp#8]
Greift auf die Datenbank zu und speichert Zeug da rein

**Comment by pranges** [comment]
DB Helper Klasse ist vorbereitet mit Einfügemethoden für unsere Gesten-Objekete

**Comment by pranges** [comment]
noch TBD:
- wie Speichern (ganz am Schluss)
- Verwaltung der Objekte, während die App läuft
- evtl csv

**Comment by JonasMa** [comment]
User DB braucht noch startzeiten je Activity als Spalten

**Comment by JonasMa** [comment]
Exportieren als .csv
